// Generated by https://quicktype.io

export interface ItunesTypes {
  resultCount?: number;
  results?: Result[];
}

export interface Result {
  wrapperType: string;
  collectionType: string;
  artistId: number;
  collectionId: number;
  amgArtistId?: number;
  artistName: string;
  collectionName: string;
  collectionCensoredName: string;
  artistViewUrl?: string;
  collectionViewUrl: string;
  artworkUrl60: string;
  artworkUrl100: string;
  collectionPrice: number;
  collectionExplicitness: string;
  contentAdvisoryRating?: string;
  trackCount: number;
  copyright: string;
  country: string;
  currency: number;
  releaseDate: string;
  primaryGenreName: string;
}

// export enum CollectionExplicitness {
//     Cleaned = "cleaned",
//     Explicit = "explicit",
//     NotExplicit = "notExplicit",
// }

// export enum CollectionType {
//     Album = "Album",
// }

// export enum ContentAdvisoryRating {
//     Clean = "Clean",
//     Explicit = "Explicit",
// }

// export enum Country {
//     Usa = "USA",
// }

// export enum Currency {
//     Usd = "USD",
// }

// export enum WrapperType {
//     Collection = "collection",
// }
